ex2ClickandFit/src/Entity/Anounce.php
<?php

namespace App\Entity;

use App\Repository\AnounceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnounceRepository::class)]
class Anounce
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Photo = null;

    #[ORM\Column(length: 255)]
    private ?string $Phone = null;

    #[ORM\Column(length: 255)]
    private ?string $PostalCode = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Date = null;

    #[ORM\ManyToOne(inversedBy: 'anounces')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(?string $Photo): self
    {
        $this->Photo = $Photo;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(string $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->PostalCode;
    }

    public function setPostalCode(string $PostalCode): self
    {
        $this->PostalCode = $PostalCode;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

ex2ClickandFit/src/Controller/AnouncesController.php
<?php

namespace App\Controller;

use App\Entity\Anounce;
use App\Form\AnounceFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AnouncesController extends AbstractController
{
    private $em;
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    #[Route('/menu', name: 'Menu')]    
    public function index(): Response
    {
        $anounces = $this->em->getRepository(Anounce::class)->findAll();

        return $this->render('anounces/index.html.twig', ["Anounces" => $anounces]);
    }
    
    #[Route('/anounce/new', name: "Nouvelle annonce")]
    public function create(Request $request): Response
    {
        if ($this->getUser() == NULL) {
            return $this->redirectToRoute('Menu');
        }
        $anounce = new Anounce;
        $form = $this->createForm(AnounceFormType::class, $anounce);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $newAnounce = $form->getData();
            $image = $form->get('Photo')->getData();
            if ($image) {
                $newImage = uniqid() . '.'  . $image->guessExtension();
                try {
                    $image->move($this->getParameter('kernel.project_dir') . '/public/uploads', $newImage);
                } catch (FileException $e) {
                    return new Response($e->getMessage());
                }

                $newAnounce->setPhoto('/uploads/' . $newImage);
            }
            $newAnounce->setPhone($this->getUser()->getPhone());
            $newAnounce->setDate(new \DateTime('@'.strtotime('now')));
            $newAnounce->setUser($this->getUser());
            
            $this->em->persist($newAnounce);
            $this->em->flush();

            return $this->redirectToRoute('Menu');
        }
    
        return $this->render('anounces/new.html.twig', ['form' => $form->createView()]);
    }

    #[Route('/anounce/{id}/edit', name: "Edition annonce")]
    public function edit($id, Request $request): Response
    {
        if ($this->getUser() == NULL) {
            return $this->redirectToRoute('Menu');
        }
        $anounce = $this->em->getRepository(Anounce::class)->find($id);
        $form = $this->createForm(AnounceFormType::class, $anounce);

        if ($this->getUser()->getId() != $anounce->getUser()->getId()) {
            return $this->redirectToRoute('Menu');
        }

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('Photo')->getData();
            if ($image) {
                if ($anounce->getImagePath() !== null) {
                    if (file_exists( $this->getParameter('kernel.project_dir') . $anounce->getImagePath())) {
                        $this->GetParameter('kernel.project_dir') . $anounce->getImagePath();
                    }
                    $newImage = uniqid() . '.'  . $image->guessExtension();
                    try {
                        $image->move($this->getParameter('kernel.project_dir') . '/public/uploads', $newImage);
                    } catch (FileException $e) {
                        return new Response($e->getMessage());
                    }

                    $anounce->setPhoto('/uploads/' . $newImage);
                }
            }
            $anounce->setTitle($form->get('Title')->getData());
            $anounce->setDescription($form->get('Description')->getData());
            $anounce->setPostalCode($form->get('PostalCode')->getData());
            
            $this->em->flush();
            return $this->redirectToRoute('Détail', ['id' => $id]);
        }
    
        return $this->render('anounces/edit.html.twig', ['anounce' => $anounce, 'form' => $form->createView()]);
    }

    #[Route('/anounce/{id}/delete', name: "Supprimer")]
    public function delete($id): Response
    {
        if ($this->getUser() == NULL) {
            return $this->redirectToRoute('Menu');
        }
    
        $anounce = $this->em->getRepository(Anounce::class)->find($id);

        if ($this->getUser()->getId() != $anounce->getUser()->getId()) {
            return $this->redirectToRoute('Menu');
        }

        $this->em->remove($anounce);
        $this->em->flush();

        return $this->redirectToRoute('Menu');
    }

    #[Route('/anounce/{id}', name: "Détail")]
    public function show($id): Response
    {
        $anounce = $this->em->getRepository(Anounce::class)->find($id);

        return $this->render('anounces/show.html.twig', ["Anounce" => $anounce]);
    }
}

ex2ClickandFit/templates/anounces/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer{% endblock %}

{% block body %}

{{ form_start(form) }}
{{ form_widget(form) }}
<button type="submit">Modifier l'anonce</button>
{{ form_end(form) }}

{% endblock %}

ex2ClickandFit/templates/anounces/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Menu{% endblock %}

{% block body %}

{% if app.user %}
<button><a href="/anounce/new">Créer une annonce</a></button>
{% endif %}

{% for anounce in Anounces %}
    <h2> {{ anounce.title }} </h2>

    {% if anounce.photo %}
        <img src="{{anounce.photo}}" alt="">
    {% else %}
        <img src="build/images/noImage.e00652fb.jpg" alt="">           
    {% endif %}

    <button><a href="/anounce/{{ anounce.id }}">Voir l'annonce</a></button>
{% endfor %}

{% endblock %}

ex2ClickandFit/templates/anounces/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer{% endblock %}

{% block body %}

{{ form_start(form) }}
{{ form_widget(form) }}
<button type="submit">Créer l'anonce</button>
{{ form_end(form) }}

{% endblock %}

ex2ClickandFit/templates/anounces/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail{% endblock %}

{% block body %}

<button><a href="/menu">Retour au menu</a></button>

<h1>{{ Anounce.title }}</h1>

{% if Anounce.photo %}
    <img src="{{ Anounce.photo }}" alt="">
{% else %}
    <img src="../build/images/noImage.e00652fb.jpg" alt="">           
{% endif %}

<h3>{{ Anounce.postalCode }}</h3>

<p>{{ Anounce.description }}</p>

<p>Téléphone: {{ Anounce.phone }}</p>

{% if app.user %}
    {% if app.user.id == Anounce.user.id %}
        <button><a href="/anounce/{{ Anounce.id }}/edit">Modifier l'annonce</a></button>
        <button><a class="pl-10" href="/anounce/{{ Anounce.id }}/delete">Supprimer l'annonce</a></button>
    {% endif %}
{% endif %}

{% endblock %}